language: python

services:
  - docker

before_install:
  - cd api-tester
  - docker build -t andem/tcmg412-tester .
  - cd ../flask-api
  - docker build -t andem/tcmg412-api .
  - docker-compose up d
  - docker ps

script:
  - docker run andem/tcmg412-tester
